<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Homework Number 1</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>


<!-- MathJax scripts -->
<script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>



</head>

<body>
<h1>Homework Number 1</h1>

<h2>Names: FirstName1 LastName1, FirstName1 LastName2, FirstName3 LastName3</h2>

<p>This work was last compiled on Tuesday, February 04, 2014 - 10:42:08 AM.</p>

<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 3.0.2
</code></pre>

<p><strong>Prob 1:</strong> Access the data from URL 
<a href="http://www.stat.berkeley.edu/users/statlabs/data/babies.data">http://www.stat.berkeley.edu/users/statlabs/data/babies.data</a>,
and store the information in an object named <code>BABIES</code> using the function 
<code>read.table()</code>. A description of the variables can be found at
<a href="http://www.stat.berkeley.edu/users/statlabs/labs.html">http://www.stat.berkeley.edu/users/statlabs/labs.html</a>.  These data are a subset from a much larger study dealing with 
child health and development.  Use the functions <code>summary()</code> and <code>dim()</code> on <code>BABIES</code>, and report the number of rows and columns of <code>BABIES</code>.</p>

<pre><code class="r"># 
BABIES &lt;- read.table(&quot;http://www.stat.berkeley.edu/users/statlabs/data/babies.data&quot;, header = TRUE)
summary(BABIES)
</code></pre>

<pre><code>      bwt        gestation       parity           age           height         weight        smoke      
 Min.   : 55   Min.   :148   Min.   :0.000   Min.   :15.0   Min.   :53.0   Min.   : 87   Min.   :0.000  
 1st Qu.:109   1st Qu.:272   1st Qu.:0.000   1st Qu.:23.0   1st Qu.:62.0   1st Qu.:115   1st Qu.:0.000  
 Median :120   Median :280   Median :0.000   Median :26.0   Median :64.0   Median :126   Median :0.000  
 Mean   :120   Mean   :287   Mean   :0.255   Mean   :27.4   Mean   :64.7   Mean   :154   Mean   :0.464  
 3rd Qu.:131   3rd Qu.:288   3rd Qu.:1.000   3rd Qu.:31.0   3rd Qu.:66.0   3rd Qu.:140   3rd Qu.:1.000  
 Max.   :176   Max.   :999   Max.   :1.000   Max.   :99.0   Max.   :99.0   Max.   :999   Max.   :9.000  
</code></pre>

<pre><code class="r">dim(BABIES)
</code></pre>

<pre><code>[1] 1236    7
</code></pre>

<blockquote>
<p><strong>Prob 1 answer:</strong> There are <strong>1236</strong> rows and <strong>7</strong> columns in the data frame <code>BABIES</code>.</p>
</blockquote>

<p><strong>Prob 2:</strong> The variables <code>bwt</code>, <code>gestation</code>, <code>parity</code>, <code>age</code>, <code>height</code>, <code>weight</code>, and <code>smoke</code> use values of 999, 999, 9, 99, 99, 999, and 9, respectively, to denote &#39;&#39;unknown.&#39;&#39;  <code>R</code> uses <code>NA</code> to denote a missing or unavailable value.  Re-code the missing values in <code>BABIES</code>.  Hint: use something similar to <code>BABIES$bwt[BABIES$bwt == 999] = NA</code>.  Run the functions <code>summary()</code> and <code>dim()</code> on your <code>BABIES</code> data frame.</p>

<pre><code class="r">BABIES$bwt[BABIES$bwt == 999] = NA
BABIES$gestation[BABIES$gestation == 999] = NA
BABIES$parity[BABIES$parity == 9] = NA
BABIES$age[BABIES$age == 99] = NA
BABIES$height[BABIES$height == 99] = NA
BABIES$weight[BABIES$weight == 999] = NA
BABIES$smoke[BABIES$smoke == 9] = NA
summary(BABIES)
</code></pre>

<pre><code>      bwt        gestation       parity           age           height       weight        smoke      
 Min.   : 55   Min.   :148   Min.   :0.000   Min.   :15.0   Min.   :53   Min.   : 87   Min.   :0.000  
 1st Qu.:109   1st Qu.:272   1st Qu.:0.000   1st Qu.:23.0   1st Qu.:62   1st Qu.:115   1st Qu.:0.000  
 Median :120   Median :280   Median :0.000   Median :26.0   Median :64   Median :125   Median :0.000  
 Mean   :120   Mean   :279   Mean   :0.255   Mean   :27.3   Mean   :64   Mean   :129   Mean   :0.395  
 3rd Qu.:131   3rd Qu.:288   3rd Qu.:1.000   3rd Qu.:31.0   3rd Qu.:66   3rd Qu.:139   3rd Qu.:1.000  
 Max.   :176   Max.   :353   Max.   :1.000   Max.   :45.0   Max.   :72   Max.   :250   Max.   :1.000  
               NA&#39;s   :13                    NA&#39;s   :2      NA&#39;s   :22   NA&#39;s   :36    NA&#39;s   :10     
</code></pre>

<pre><code class="r">dim(BABIES)
</code></pre>

<pre><code>[1] 1236    7
</code></pre>

<p><strong>Prob 3:</strong> Use the function <code>na.omit()</code> to create a &#39;&#39;clean&#39;&#39; data set that removes subjects if any observations on the subject are &#39;&#39;unknown.&#39;&#39;   Store the modified data frame in a data frame named <code>CLEAN</code>.  Run the function <code>dim()</code> on the data frame <code>CLEAN</code>.  </p>

<pre><code class="r">CLEAN &lt;- na.omit(BABIES)
dim(CLEAN)
</code></pre>

<pre><code>[1] 1174    7
</code></pre>

<p><strong>Prob 4:</strong> How many missing values in the data frame <code>BABIES</code> are there for <code>gestation</code>, <code>age</code>, <code>height</code>, <code>weight</code>, and <code>smoke</code>, respectively?  How many rows of <code>BABIES</code> have no missing values, one missing value, two missing values, and three missing values, respectively?  Note: the number of rows in <code>CLEAN</code> should agree with your answer for the number of rows in <code>BABIES</code> that have no missing values.</p>

<pre><code class="r">sum(is.na(BABIES$gestation))
</code></pre>

<pre><code>[1] 13
</code></pre>

<pre><code class="r">sum(is.na(BABIES$age))
</code></pre>

<pre><code>[1] 2
</code></pre>

<pre><code class="r">sum(is.na(BABIES$height))
</code></pre>

<pre><code>[1] 22
</code></pre>

<pre><code class="r">sum(is.na(BABIES$weight))
</code></pre>

<pre><code>[1] 36
</code></pre>

<pre><code class="r">sum(is.na(BABIES$smoke))
</code></pre>

<pre><code>[1] 10
</code></pre>

<pre><code class="r">table(apply(is.na(BABIES), 1, sum))
</code></pre>

<pre><code>
   0    1    2    3 
1174   43   17    2 
</code></pre>

<blockquote>
<p><strong>Prob 4 answer:</strong> 
1174, 43, 17, 2</p>
</blockquote>

<p><strong>Prob 5:</strong> Sort the values in <code>CLEAN</code> by <code>bwt</code>, <code>gestation</code>, and <code>age</code>.  Store the sorted values in a data frame named <code>BGA</code> and show the last six rows of <code>BGA</code>.</p>

<pre><code class="r"># BGA&lt;-CLEAN[order(CLEAN$bwt,CLEAN$gestation,CLEAN$age),]) BGA&lt;-CLEAN[order(CLEAN$bwt,CLEAN$gestation,CLEAN$age)]
BGA &lt;- CLEAN[1:4]
summary(BGA)
</code></pre>

<pre><code>      bwt        gestation       parity           age      
 Min.   : 55   Min.   :148   Min.   :0.000   Min.   :15.0  
 1st Qu.:108   1st Qu.:272   1st Qu.:0.000   1st Qu.:23.0  
 Median :120   Median :280   Median :0.000   Median :26.0  
 Mean   :119   Mean   :279   Mean   :0.262   Mean   :27.2  
 3rd Qu.:131   3rd Qu.:288   3rd Qu.:1.000   3rd Qu.:31.0  
 Max.   :176   Max.   :353   Max.   :1.000   Max.   :45.0  
</code></pre>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 6:</strong> Store the data frame <code>CLEAN</code> in your working directory as a <code>*.csv</code> file using the function <code>write.csv()</code> using the argument <code>row.names = FALSE</code>.
Use the function <code>read.csv()</code> to read the file back in to your working directory and store
the result in <code>NAELC</code>.  Show the first six rows of the data frame <code>NAELC</code>.  </p>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 7:</strong> What percent of the women in <code>CLEAN</code> are pregnant with their first child (<code>parity = 0</code>) and do not smoke?</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 7 answer:</strong> </p>
</blockquote>

<p><strong>Prob 8:</strong> Use the information in <code>CLEAN</code> to create a density histogram of the birth weights of babies whose mothers have never smoked (<code>smoke = 0</code>) and another histogram placed directly below the first in the same graphics device for the birth weights of babies whose mothers currently smoke (<code>smoke = 1</code>).  Make the range of the \( x \)-axis 50 to 180 (ounces) for both histograms.  Superimpose a density curve over each histogram, and label the \( x \)-axis &ldquo;Weight in Ounces&rdquo;.  <em>Extra credit if you create the requested graph with the three graphic systems (base, lattice, and ggplot2).</em></p>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 9:</strong> Based on the histograms, characterize the distribution of baby birth weight for both non-smoking and smoking mothers.</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 9 answer:</strong> </p>
</blockquote>

<p><strong>Prob 10:</strong> Create side-by-side boxplots to compare the birth weights of babies whose mother&#39;s never smoked and those who currently smoke.  Use base graphs (<code>boxplot()</code>), lattice graphs (<code>bwplot()</code>), and ggplot2 graphs to create the boxplots.  Label the \( y \)-axis &ldquo;Weight in Ounces&rdquo;.</p>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 11:</strong> What is the median weight difference between babies who are firstborn
(<code>parity = 0</code>) and those who are not (<code>parity = 1</code>)?</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 11 answer:</strong> </p>
</blockquote>

<p><strong>Prob 12:</strong> Create a single graph of the densities for pre-pregnancy <code>weight</code> for mothers who have never smoked and for mothers who currently smoke.  Make sure both densities appear in the same graph and have a legend.  Label the \( x \)-axis &ldquo;Weight in Pounds&rdquo;.  <em>Extra credit if you create the requested graph using base, lattice, and ggplot2 graphics.</em></p>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 13:</strong> Characterize the pre-pregnancy distribution of <code>weight</code> for mothers who have never smoked and for mothers who currently smoke.</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 13 answer:</strong> </p>
</blockquote>

<p><strong>Prob 14:</strong> What is the mean pre-pregnancy weight difference between mothers who do not smoke and those who do?  Can you think of any reasons not to use the mean as a measure of center to compare pre-pregnancy weights in this problem?</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 14 answer:</strong> </p>
</blockquote>

<p><strong>Prob15:</strong> Compute the body mass index (<code>BMI</code>) for each mother in <code>CLEAN</code>.  Recall that <code>BMI</code> is defined as \( \text{kg}/\text{m}^2 \) (0.0254 m = 1 in., and 0.45359 kg = 1 lb.).  Add the variables weight in kg, height in m, and BMI to <code>CLEAN</code> and store the result in <code>CLEANP</code>.  Show the first six rows of <code>CLEANP</code>.</p>

<pre><code class="r"># 
</code></pre>

<p><strong>Prob 16:</strong> Characterize the distribution of BMI.  Create either a histogram or density plot to
help determine the shape of the BMI distribution.  Label the \( x \)-axis &ldquo;BMI (\( kg/m^2 \))&rdquo;.</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 16 answer:</strong> </p>
</blockquote>

<p><strong>Prob 17:</strong> Group pregnant mothers according to their BMI quartile. Find the mean and standard deviation for baby birth weights in each quartile for mothers who have never smoked and those who currently smoke.   Find the median and IQR for baby birth weights in each quartile for mothers who have never smoked and those who currently smoke. Based on your answers, would you characterize birth weight in each group as relatively symmetric or skewed? Create histograms and densities of <code>bwt</code> conditioned on <code>BMI</code> quartiles and whether the mother smokes to verify your previous assertions about the shape.</p>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 17 answer:</strong>  </p>
</blockquote>

<p><strong>Prob 18:</strong> Create side-by-side boxplots of <code>bwt</code> based on whether the mother
smokes conditioned on <code>BMI</code> quartiles.  What do you notice using the boxplots?</p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 18 answer:</strong> </p>
</blockquote>

<p><strong>Prob 19:</strong> Does it appear that BMI is related to the birth weight of a baby? Create a scatterplot of birth weight (<code>bwt</code>) versus <code>BMI</code> while conditioning on BMI quartiles and whether the mother smokes to help answer the question.  Use <code>log(bwt)</code> on the \( y \)-axis instead of the untransformed <code>bwt</code>.</p>

<pre><code class="r">#
</code></pre>

<blockquote>
<p><strong>Prob 19 answer:</strong> </p>
</blockquote>

<p><strong>Prob 20:</strong> Create a scatterplot of <code>bwt</code> versus <code>gestation</code> conditioned on BMI quartiles and whether the mother smokes using <code>ggplot2</code> graphics.  Fit curves to the data using <code>loess</code> and <code>lm</code> (<code>stat_smooth()</code>); and display the fitted curves in the scatterplots. What do you find interesting about the resulting graphs? </p>

<pre><code class="r"># 
</code></pre>

<blockquote>
<p><strong>Prob 20 answer:</strong>  </p>
</blockquote>

</body>

</html>

